kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: ci

steps:
- name: build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker build -t klinux/api:v1 .
