---
kind: pipeline
type: kubernetes
name: k8s-python-build

metadata:
  namespace: ci

steps:
- name: ci
  image: plugins/docker
  pull: if-not-exists
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/
  settings:
    tags: ${DRONE_TAG}
  commands:
  - docker build -t klinux/api:v1 .

- name: create-image
  image: plugins/docker
  pull: if-not-exists
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/
  environment:
    DOCKER_USER:
      from_secret: docker_user
    DOCKER_PASS:
      from_secret: docker_pass
  settings:
    tags: ${DRONE_TAG}
  commands:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  when:
  branch:
    - develop

volumes:
- name: dockersock
  host:
    path: /var/run