---
kind: pipeline
type: kubernetes
name: k8s-python-pipeline

metadata:
  namespace: ci

steps:
- name: build
  image: plugins/docker
  privileged: true
  commands:
  - docker build -t klinux/api:v1 .
