---
kind: pipeline
type: kubernetes
name: k8s-python-build

metadata:
  namespace: ci

steps:
- name: build
  image: plugins/docker
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/
  environment:
    DOCKER_USER:
      from_secret: docker_user
    DOCKER_PASS:
      from_secret: docker_pass
  settings:
    tags: ${DRONE_TAG}
  commands:
  - docker build -t klinux/api:v1 .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

volumes:
- name: dockersock
  host:
    path: /var/run